### ISSUE TITLE
Non-worker pool example should complete.

### ISSUE THREAD

**Issue by delaneyj** [cloudnc/observable-webworker#37] opened 2019-12-24 16:31 UTC
Example working however when I change to console out when completing nothing happens.

```
const input$ = of('Hello from main thread')
  fromWorker<string, string>(
    () => new Worker('./hello.worker', { type: 'module' }),
    input$,
  ).subscribe(
    message => {
      console.log(message) // Outputs 'Hello from webworker'
    },
    console.error,
    () => {
      console.log(`Hello Worker done`)
    },
  )
```

It's only when I add a `take(1)` to the worker's pipe that it actually completes.  
```
@ObservableWorker()
export class HelloWorker implements DoWork<string, string> {
  public work(input$: Observable<string>): Observable<string> {
    return input$.pipe(
      map(message => {
        console.log(message) // outputs 'Hello from main thread'
        return `Hello from webworker`
      }),
      take(1),
    )
  }
}
```

This seems incorrect as `of` send a `complete` right after the `next` [as shown here](https://jsbin.com/fahosugusu/edit?js,console).  Hopefully I'm just missing something in how to use properly.

**Comment by zakhenry** [comment] 2020-01-07 17:42
@delaneyj I think I may not be understanding the issue here - observable worker does not assume that the worker will return only one result. In the case that the worker does not return a completing stream, this is mirrored to the main thread - it will never complete if the worker does not complete the stream.

**Comment by delaneyj** [comment] 2020-01-20 07:24
`take(1)` in this example does complete the stream.  I ended up writing my own version that handled this.

**Comment by zakhenry** [comment] 2020-01-20 08:42
@delaneyj are you saying that you would expect that if a worker returns a non completing stream the observable in the main thread would take the first result then complete? If so then the correct thing to do is either have the worker take(1) or the main thread take(1).

If you’re saying that a worker thread that returns a completing observable is not causing the main thread to complete, then that would be a bug that I should fix :)

**Comment by delaneyj** [comment] 2020-01-20 22:59
> If you’re saying that a worker thread that returns a completing observable is not causing the main thread to complete, then that would be a bug that I should fix :)

That's what I'm saying :P

**Comment by zakhenry** [comment] 2020-01-20 23:41
Oh! I've dug into this issue and I think I still misunderstood what you're saying. So basically the behavior that you're experiencing is actually as intended (you can see a test for this in https://github.com/cloudnc/observable-webworker/blob/7bae3b69e7cfc7c94a51d4385222f8707e69c152/projects/observable-webworker/src/lib/from-worker.spec.ts#L66-L93), but there is a bit of nuance in the logic of how an observable is passed to a worker.

---

It is best to think of the return result from the worker as the inner observable returned from a `mergeMap` - multiple responses are acceptable, and even no response at all. Just like a `mergeMap`, it is expected that the original input source does not effect the completion status of the overall observable.

e.g.
```ts
const example$ = of(true).pipe(
  mergeMap(() => interval(500)),
);

example$.subscribe({
  complete: () => console.log('completed'),
  next: (v) => console.log('next', v),
})
```

In the above example, the inner observable returned from the `mergeMap` is a non-completing observable, which means that `example$` will also never complete.

Change the inner observable to complete:

```ts
const example$ = of(true).pipe(
  mergeMap(() => interval(500).pipe(take(1))),
);

example$.subscribe({
  complete: () => console.log('completed'),
  next: (v) => console.log('next', v),
})
```

And it will complete the result.

---

This behavior is intentional as otherwise we would terminate the webworker as soon as the `input$` observable completed, thus causing the webworker to fail to do any work. Likewise if we opted to instead wait for the webworker to emit its first value then complete, we're preventing the worker from being able to emit multiple values. Instead, we expect either a) the webworker to signal it is done by completing the observable, or b) the main thread calling function to unsubscribe from the resulting observable.

---

I hope this makes sense this time :) If I'm still off base it might be useful to provide a better example that showcases the problem (or the fix that you added).

**Comment by zakhenry** [comment] 2020-04-24 22:24
Closing as I believe this is working as intended. Please do ping if you have a repro demonstrating the issue

**Closed by zakhenry** 2020-04-24 22:24 UTC
